<a href="https://colab.research.google.com/github/sarthakksingh2/Sarthak-ML/blob/main/Credit_Card_Fraud.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [29]:
credited_card_df = pd.read_csv('creditcard.csv')

In [ ]:
credited_card_df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
5665,5921,-2.229818,2.247262,0.616172,-0.075552,-0.696383,-0.307728,-0.320726,0.904834,1.078978,...,-0.247700,-0.621363,0.188980,0.125309,-0.186595,0.013333,-0.081032,0.147845,10.48,0.0
3684,3143,-3.694439,0.420388,0.619713,-0.849952,1.114947,-0.062059,1.102801,-1.183754,1.047685,...,-0.385597,-0.589252,-0.032500,-0.829957,-0.106382,-0.263091,-3.017305,0.873272,1.98,0.0
4638,4013,0.396462,-1.061374,-0.143748,-3.573015,-0.763387,0.578597,-0.417008,-0.796022,2.204338,...,0.422330,-0.516262,0.228554,-1.436665,0.288653,-0.919091,0.284944,0.298476,155.57,0.0
6855,8715,-0.447418,0.424726,3.214006,3.781284,-1.266217,1.173467,-0.798863,0.321206,1.812212,...,0.101545,1.093534,-0.012159,0.746856,-1.006230,0.265739,0.225412,0.197598,68.30,0.0
6848,8688,1.393336,-0.749140,0.963299,-0.599487,-1.155472,0.315264,-1.432903,0.177104,1.116584,...,0.138847,0.673284,-0.187811,-0.529791,0.488206,-0.047088,0.014558,-0.002931,0.50,0.0

In [30]:
credited_card_df.shape

(13954, 31)

In [31]:
credited_card_df['Class'].value_counts()

Class
0.0    13897
1.0       56
Name: count, dtype: int64

where, 1 : Fraud Transaction & 0 : Legitamate Transaction

In [32]:
credited_card_df.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,...,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13954.000000,13953.000000,13953.000000
mean,10121.161817,-0.235676,0.284287,0.846047,0.302775,-0.118730,0.128013,-0.157297,-0.016148,0.989827,...,-0.068037,-0.157471,-0.035585,0.011158,0.117019,0.035544,0.012787,0.002122,63.882442,0.004013
std,7739.625811,1.720315,1.394804,1.561376,1.500595,1.289494,1.320395,1.238583,1.262024,1.214044,...,0.873942,0.621845,0.499807,0.587225,0.427953,0.558290,0.399550,0.255710,177.887021,0.063227
min,0.000000,-27.670569,-34.607649,-24.667741,-4.657545,-32.092129,-23.496714,-26.548144,-23.632502,-7.175097,...,-11.468435,-8.593642,-19.254328,-2.512377,-4.781606,-1.338556,-7.976100,-3.575312,0.000000,0.000000
25%,2984.250000,-0.969786,-0.282728,0.407297,-0.623141,-0.717155,-0.624025,-0.616307,-0.182270,0.288101,...,-0.271778,-0.549723,-0.173807,-0.339656,-0.135887,-0.374596,-0.076862,-0.014869,5.490000,0.000000
50%,9086.500000,-0.319439,0.252904,0.960978,0.220104,-0.191627,-0.144198,-0.111960,0.016945,0.971414,...,-0.132304,-0.122777,-0.045041,0.060208,0.155162,-0.035825,-0.000950,0.016238,15.690000,0.000000
75%,17103.500000,1.162662,0.884741,1.607031,1.198942,0.351255,0.508494,0.421830,0.265736,1.654184,...,0.018677,0.228997,0.069750,0.392734,0.393032,0.375271,0.098516,0.072497,52.150000,0.000000
max,24759.000000,1.960497,10.558600,4.101716,11.927512,34.099309,21.393069,34.303177,10.535558,10.392889,...,22.614889,4.534454,13.876221,3.200201,5.525093,3.517346,8.254376,4.860769,7712.430000,1.000000

In [33]:
legit = credited_card_df[credited_card_df.Class == 0]
fraud = credited_card_df[credited_card_df.Class == 1]

In [34]:
fraud.shape

(56, 31)

In [35]:
legit.shape

(13897, 31)

In [36]:
legit_sample = legit.sample(n=492)
credited_card_df = pd.concat([legit_sample, fraud], axis=0)

In [37]:
credited_card_df['Class'].value_counts()

Class
0.0    492
1.0     56
Name: count, dtype: int64

In [38]:
credited_card_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,10856.920732,-0.294937,0.305078,0.820501,0.260808,-0.092734,0.110527,-0.081220,-0.015479,1.108480,...,0.045347,-0.068615,-0.169297,-0.018045,-0.001357,0.130543,0.029287,0.036124,0.004094,65.891850
1.0,12262.107143,-4.727948,4.660436,-9.328536,6.783464,-2.890388,-2.030360,-6.578337,1.028374,-2.981468,...,0.453283,0.116896,0.048132,-0.225526,-0.452514,-0.124184,0.333325,0.793484,-0.046177,90.815893

In [39]:
x = credited_card_df.drop('Class', axis=1)
y = credited_card_df['Class']

In [40]:
x.shape

(548, 30)

In [41]:
y.shape

(548,)

In [42]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=2)

In [43]:
model = LogisticRegression()
model.fit(x_train, y_train)
ypred = model.predict(x_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [44]:
score = accuracy_score(ypred,y_test)
print("Accuracy score on Test Data is ",score)

Accuracy score on Test Data is  0.9636363636363636

In [45]:
xpred = model.predict(x_train)
training_data_accuracy = accuracy_score(xpred,y_train)

In [46]:
print("Accuracy score on Training Data is ",training_data_accuracy)

Accuracy score on Training Data is  0.9863013698630136